apiVersion: v1
kind: Command
metadata:
  name: 换老婆
  label: {en_US: Change Waifu, zh_Hans: 换老婆}
  description: {en_US: Spend points to redraw today's waifu., zh_Hans: 消耗积分重新抽取今日老婆。}
spec: {}
execution:
  python:
    path: change_wife.py
    attr: ChangeWife
