apiVersion: v1
kind: Command
metadata:
  name: 排行榜
  label: {en_US: Leaderboard, zh_Hans: 积分排行榜}
  description: {en_US: Show the top 10 users by points., zh_Hans: 查看积分排行榜前十名。}
spec: {}
execution:
  python:
    path: leaderboard.py
    attr: Leaderboard
