apiVersion: v1
kind: Command
metadata:
  name: 老婆
  label: {en_US: Daily Waifu, zh_Hans: 今日老婆}
  description: {en_US: Draw or change today's waifu., zh_Hans: 抽取或重抽今日老婆。}
spec: {}
execution:
  python:
    path: waifu.py
    attr: Waifu
